name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write 
    steps:
      - run: echo "build code"
      - run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/gnowleumas/gnowleumas2-pub-repo1/actions/workflows
      - run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'authorization: Bearer ${{ secrets.WFD }}' \
            https://api.github.com/repos/gnowleumas/gnowleumas2-pub-repo1/actions/workflows/27118217/dispatches \
            -d '{"ref":"master"}'
