name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: arc-action-runner-cj
    steps:
      - run: echo "build code"
      - run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Sitecore-PD-Sandbox/cd-workflow-poc-2/actions/workflows
